export const INSERT_ITEM = "@@wecreatesoftware/redux-higher-order-reducers/insert-item"
export const REMOVE_ITEM = "@@wecreatesoftware/redux-higher-order-reducers/remove-item"
export const REMOVE_ITEM_BY_KEY = "@@wecreatesoftware/redux-higher-order-reducers/remove-item-by-key"
export const UPDATE_ITEM = "@@wecreatesoftware/redux-higher-order-reducers/update-item"
export const UPDATE_ITEM_BY_KEY = "@@wecreatesoftware/redux-higher-order-reducers/update-item-by-key"
export const UPDATE_ITEMS_BY_KEY = "@@wecreatesoftware/redux-higher-order-reducers/update-items-by-key"
export const RESET_LIST = "@@wecreatesoftware/redux-higher-order-reducers/reset-list"
export const SET_LIST = "@@wecreatesoftware/redux-higher-order-reducers/set-list"
