version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: npm-check-updates
    versions:
    - 11.1.1
    - 11.1.10
    - 11.1.4
    - 11.1.8
    - 11.1.9
    - 11.2.0
    - 11.2.2
    - 11.4.1
    - 11.5.1
    - 11.5.3
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.1
    - 2.41.2
    - 2.41.3
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.2
    - 2.42.4
    - 2.44.0
    - 2.45.0
    - 2.45.1
    - 2.45.2
  - dependency-name: "@babel/core"
    versions:
    - 7.13.1
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/cli"
    versions:
    - 7.13.14
  - dependency-name: "@babel/register"
    versions:
    - 7.13.0
    - 7.13.14
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.13.0
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.0
    - 7.13.5
    - 7.13.8
    - 7.13.9
