export const OBJECT_REDUCER1 = "OBJECT_REDUCER1"
export const OBJECT_REDUCER2 = "OBJECT_REDUCER2"
export const OBJECT_REDUCER_EXTENDED = "OBJECT_REDUCER_EXTENDED"
export const UPDATE_OBJECT_TIMESTAMP = "UPDATE_OBJECT_TIMESTAMP"
